channels:
  - plotly
  - anaconda
  - grst
  - bioconda
  - conda-forge
  - defaults
  - brinkerhoffc
dependencies:
  - r-base
  - r-rstan
  - r-rstantools
  - r-rstanarm
  - r-cmdstanr
  - r-codetools
  - r-scatterpie
  - openmp
  - libclang
  - r-coda
  - r-mvtnorm
  - r-devtools
  - r-dagitty
  - r-loo
  - r-shape
  - r-irkernel
  - jupyterlab
  - rise
  - r-remotes
