#!/bin/bash

#while getopts c: option
#do
#    case "${option}"
#    in
#        c) COURSE=${OPTARG};;
#        \?) ## Invalid option
#            printf "Error: invalid option.\n\n"
#            exit;;
#    esac
#done

#if [ "${COURSE}" == "Intro_to_NGS" ]

#${CONDA_DIR}/envs/rethinking_R/bin/R -e "IRkernel::installspec(user=TRUE, name = 'rethinking_R', displayname = 'rethinking_R')"

bash -c "jupyter lab --NotebookApp.token='' "



